name: Deploy MultiK8s
on:
  workflow_run:
    workflows: Frontend unit tests
    branches: [master]
    types: completed
 
env:
  SHA: $(git rev-parse HEAD)
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t dave123456789/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true dave123456789/react-test npm test
 
      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
 
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          #project_id: multi-k8s-take2
          project_id: multi-k8s-take3
      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker
 
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          #cluster_name: multi-cluster1
          cluster_name: multi-cluster3
          location: us-west2-a
 
      - name: Build
      # use unique naming for builds here so that I don't overwrite the elastic beanstalk 10-14 images
      # note that no nginx images needed because routing done via ingress-service.yaml with K8s and ingress-nginx added separately to GKE

#          docker build -t dave123456789/multi-client-k8s-gh_take2:latest -t dave123456789/multi-client-k8s-gh_take2:${{ env.SHA }} -f ./client/Dockerfile ./client
#          docker build -t dave123456789/multi-server-k8s-pgfix-gh_take2:latest -t dave123456789/multi-server-k8s-pgfix-gh_take2:${{ env.SHA }} -f ./server/Dockerfile ./server
#          docker build -t dave123456789/multi-worker-k8s-gh_take2:latest -t dave123456789/multi-worker-k8s-gh_take2:${{ env.SHA }} -f ./worker/Dockerfile ./worker
        run: |-
          docker build -t dave123456789/multi-client-k8s-gh_take3:latest -t dave123456789/multi-client-k8s-gh_take3:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t dave123456789/multi-server-k8s-pgfix-gh_take3:latest -t dave123456789/multi-server-k8s-pgfix-gh_take3:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t dave123456789/multi-worker-k8s-gh_take3:latest -t dave123456789/multi-worker-k8s-gh_take3:${{ env.SHA }} -f ./worker/Dockerfile ./worker
      
      - name: Push
      # lastest is pushed because if someone runs kubectl apply -f k8s from build directory we want to insure they load current latest (this image)

#          docker push dave123456789/multi-client-k8s-gh_take2:latest
#          docker push dave123456789/multi-server-k8s-pgfix-gh_take2:latest
#          docker push dave123456789/multi-worker-k8s-gh_take2:latest
# 
#          docker push dave123456789/multi-client-k8s-gh_take2:${{ env.SHA }}
#          docker push dave123456789/multi-server-k8s-pgfix-gh_take2:${{ env.SHA }}
#          docker push dave123456789/multi-worker-k8s-gh_take2:${{ env.SHA }}
        run: |-
          docker push dave123456789/multi-client-k8s-gh_take3:latest
          docker push dave123456789/multi-server-k8s-pgfix-gh_take3:latest
          docker push dave123456789/multi-worker-k8s-gh_take3:latest
 
          docker push dave123456789/multi-client-k8s-gh_take3:${{ env.SHA }}
          docker push dave123456789/multi-server-k8s-pgfix-gh_take3:${{ env.SHA }}
          docker push dave123456789/multi-worker-k8s-gh_take3:${{ env.SHA }}
 
      - name: Apply

#          kubectl set image deployments/server-deployment server=dave123456789/multi-server-k8s-pgfix-gh_take2:${{ env.SHA }}
#          kubectl set image deployments/client-deployment client=dave123456789/multi-client-k8s-gh_take2:${{ env.SHA }}
#          kubectl set image deployments/worker-deployment worker=dave123456789/multi-worker-k8s-gh_take2:${{ env.SHA }}
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=dave123456789/multi-server-k8s-pgfix-gh_take3:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=dave123456789/multi-client-k8s-gh_take3:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=dave123456789/multi-worker-k8s-gh_take3:${{ env.SHA }}
 