name: Frontend unit tests
on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Test
        run: |-
          docker build -t dave123456789/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true dave123456789/react-test npm test
 